;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Move.Blink",DevComment="")
+GameplayTagList=(Tag="Ability.Move.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.Move.Rewind",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Fire",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Reload",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.SwitchWeapon",DevComment="")
+GameplayTagList=(Tag="Cooldown.Move.Blink",DevComment="")
+GameplayTagList=(Tag="Cooldown.Move.Rewind",DevComment="")
+GameplayTagList=(Tag="Cooldown.Weapon.Fire",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.CurrentAmmu",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.MaxAmmu",DevComment="")
+GameplayTagList=(Tag="Weapon.Flash",DevComment="")

